// Space manual topics injected into the SDK kodax_manual tool.
//
// The SDK ships a generic manual for KodaX SDK/CLI. In Space, users ask about the
// desktop UI they can see: providers, sessions, composer, Task Dock, popouts,
// artifacts, workflows, memory, MCP, permissions, and shortcuts. These topics
// override or extend the base manual so the in-app assistant answers with the
// current Space interaction model.
//
// Treat this file as the compact AI-facing self manual for KodaX Space. It is not
// a QA checklist by itself; it is the source the agent reads when explaining what
// the product can do and how a user should operate it.

import type { KodaXManualTopicInput } from '@kodax-ai/kodax/coding';

export const SPACE_PRODUCT_NAME = 'KodaX Space';

const text = (...lines: string[]) => lines.join('\n');

export const SPACE_MANUAL_TOPICS: readonly KodaXManualTopicInput[] = [
  {
    id: 'overview',
    title: 'KodaX Space overview',
    summary:
      'KodaX Space 是 KodaX 的本地优先桌面 AI agent 工作台，面向项目、会话和可审阅工具调用。',
    body: text(
      'KodaX Space 是基于 Electron + React + TypeScript 的桌面客户端，复用 KodaX SDK 内核，不需要单独启动 sidecar。',
      '',
      '主要界面由六部分组成：左侧 Project/Session 导航，顶部 Environment Hub 与全局工具，中央对话流，右侧 Task Dock，底部 composer，以及可覆盖在右侧的 popout 面板。',
      '',
      '核心能力：多 provider/model 切换，本地项目会话，Coder 与 Partner 工作区，权限确认，计划/Diff/任务/终端/预览/MCP/Memory/Workflow popout，图片与文件输入，Artifact/Outputs 产物，repo-intelligence，以及可保存/复跑的 workflow。',
      '',
      'Coder 面向软件研发；Partner 已启用，面向 workspace-first 知识工作，提供 Sources、Knowledge Base、Outputs、checkpoint 写入和本地 policy/audit。KodaX 0.7.67 Reference External Agent 也已接入管理、Workflow 和 Task Dock。',
    ),
    aliases: ['Space', 'KodaX Space', 'KodaX-Space', '桌面端', '客户端', '桌面客户端', '工作台'],
    nextTopics: ['self-manual', 'quickstart', 'ui-map', 'composer', 'providers'],
  },
  {
    id: 'self-manual',
    title: 'What kodax_manual means in Space',
    summary: 'kodax_manual 是 AI 读取的 Space 自说明手册，帮助回答“这个工具怎么用”。',
    body: text(
      '在 Space 会话里，当用户问“怎么配 provider”“右侧面板是什么”“这个按钮怎么用”这类产品使用问题时，AI 会调用 SDK 的 kodax_manual 工具。',
      '',
      'Space 注入的 manual topics 会把默认 SDK/CLI 手册替换成桌面端语境：按钮在哪、面板做什么、快捷键是什么、哪些功能当前可用或受限。',
      '',
      '因此它可以理解为“工具的自说明/自查手册”：AI 用它核对自己对产品能力和 UI 交互的回答。但它不是完整测试用例，也不能替代人工 QA、发布清单或安全评审。',
    ),
    aliases: ['kodax_manual', 'manual', '自查手册', '自说明手册', '工具手册', '产品手册'],
    nextTopics: ['overview', 'ui-map', 'troubleshooting'],
  },
  {
    id: 'install',
    title: 'Install KodaX Space',
    summary:
      'Space 是 Electron 桌面应用，通常从 GitHub Releases 获取安装包，也可源码 npm run dev。',
    body: text(
      'KodaX Space 不作为 npm package 使用。普通用户应从 GitHub Releases 下载对应系统安装包：Windows Setup/Portable，macOS dmg，Linux AppImage/deb。',
      '',
      '首次打开可能遇到 SmartScreen 或 Gatekeeper，因为当前安装包未走公开签名渠道。确认来源可信后按系统提示继续打开。',
      '',
      '源码开发方式：git clone 仓库，npm install --include=dev，然后 npm run dev。开发模式会启动 Vite renderer 与 Electron main watch。',
    ),
    aliases: ['下载', '安装', '安装包', 'installer', 'setup', '怎么装', '怎么下载', '源码启动'],
    nextTopics: ['quickstart', 'providers'],
  },
  {
    id: 'quickstart',
    title: 'Quickstart',
    summary: '首次使用：打开项目，配置 provider，创建/选择会话，在 composer 发出任务。',
    body: text(
      '第一次使用 Space 的最短路径：',
      '',
      '1. 打开 Settings -> Providers，选择内置 provider 或 Add custom，配置 API key/base URL/model，并 Test。',
      '2. 左侧打开一个本地项目目录。项目目录会成为会话 cwd，也是工具读写文件的边界。',
      '3. 新建或选择 session。会话保存上下文、工具调用、计划、Diff、Artifact 和 workflow 记录。',
      '4. 在底部 composer 输入任务，Enter 发送。Shift+Enter 换行，Ctrl/Cmd+Enter 会把消息排到当前 turn 之后，运行中 Esc 或停止按钮可中止。',
      '5. 需要看计划、Diff、终端、预览、MCP、Memory、Workflow 时，用右侧 Task Dock 或顶部 activity popout 打开对应面板。',
    ),
    aliases: [
      '快速开始',
      '入门',
      '上手',
      '怎么用',
      'getting started',
      'how to start',
      '第一次使用',
    ],
    nextTopics: ['providers', 'composer', 'sessions', 'task-dock', 'keyboard-shortcuts'],
  },
  {
    id: 'ui-map',
    title: 'UI map',
    summary:
      'Space 的主界面：左侧项目/会话，顶部环境与活动，中央对话，右侧 Task Dock，底部 composer。',
    body: text(
      '左侧栏：项目列表、最近会话、归档项目、会话切换与项目管理。',
      '顶部：Environment Hub 显示当前项目/git/来源/运行摘要；activity 按钮打开 Preview、Diff、Terminal、Agents、MCP、Memory、Workflow 等 popout；Settings 打开配置。',
      '中央：Transcript 显示用户消息、模型回复、工具调用、权限状态、Artifact 卡片和运行事件。',
      '右侧：Task Dock 默认是 Overview；有 Artifact 时可切换 Artifact 标签。Overview 里有 Run、Plan、Agents、Workflow、Changes、Sources、Artifacts、Context 等分区。',
      '底部：composer 输入任务，选择模型、权限模式、agent mode、reasoning effort，附加文件/图片/agent/skill/slash command。',
      '浮层：Command Palette、Quick Ask、Help、Settings、权限请求、ask_user、workflow 确认、Artifact standalone window。',
    ),
    aliases: ['界面', 'UI', '布局', '主界面', '面板位置', '入口在哪', 'surface'],
    nextTopics: ['composer', 'task-dock', 'popouts', 'settings'],
  },
  {
    id: 'composer',
    title: 'Composer input',
    summary: '底部输入框负责消息、附件、文件引用、slash/skill、agent、模式和模型选择。',
    body: text(
      'composer 支持：',
      '- Enter 发送，Shift+Enter 换行，Ctrl/Cmd+Enter 以 after-turn 队列追加；运行中发送按钮变为停止按钮。',
      '- 输入 / 打开 slash command 和 skill 补全；输入 @ 打开项目路径补全；上下键在补全和历史消息中导航。',
      '- 粘贴或拖入 PNG/JPEG/WEBP 图片会生成图片 chip，单张约 6 MiB，上限 8 张。',
      '- 拖入或通过 + 菜单添加文件/文件夹：项目内优先插入 @relative/path，项目外插入 file:// 链接；草稿最多 32 个文件引用。',
      '- + 菜单还可插入 slash command、打开 connectors/MCP、查看 skills。Agent picker 会插入 @agent-name。',
      '- 底部控件可切 provider/model/reasoning、permission mode、agent mode，并显示 context window 使用情况。',
    ),
    aliases: [
      '输入框',
      'composer',
      '底部输入',
      '附件',
      '拖文件',
      '粘贴图片',
      '@文件',
      'plus menu',
      'attach',
    ],
    nextTopics: ['slash-commands', 'image-paste', 'agent-modes', 'providers', 'permissions'],
  },
  {
    id: 'providers',
    title: 'Configure LLM providers',
    summary: 'Settings -> Providers 配置内置或自定义 provider，key 优先存系统 Keychain。',
    body: text(
      '打开 Settings -> Providers，可以搜索、测试、设默认 provider，也可以 Add custom。',
      '',
      '内置 provider 包括常见云端和本地/网关类 provider。每个 provider 可配置 API key、默认 model、base URL 或环境变量来源。Key 优先存系统 Keychain；Keychain 不可用时会退回临时内存状态。',
      '',
      '自定义 provider 支持 OpenAI-compatible 与 Anthropic-compatible 协议，需要 display name、base URL、credential、default model，以及可选 model list/reasoning 声明。只在信任内部网关时跳过 base URL 安全校验。',
      '',
      '会话内可通过模型选择器、/provider、/model、/reasoning 或 /thinking 调整当前运行配置。',
    ),
    aliases: [
      'provider',
      'API key',
      '配置 provider',
      '配 key',
      '配置 API',
      '换模型',
      '模型设置',
      'custom provider',
    ],
    nextTopics: ['custom-providers', 'settings', 'agent-modes', 'config'],
  },
  {
    id: 'custom-providers',
    title: 'Custom providers',
    summary: 'Settings -> Providers -> Add custom 添加 OpenAI/Anthropic 兼容网关或自建模型。',
    body: text(
      'Add custom 用于内部网关、自建模型、OpenAI-compatible 服务或 Anthropic-compatible 服务。',
      '',
      '需要填写：显示名、协议、base URL、credential 方式、默认模型。可补充模型列表和 reasoning effort 声明，让模型选择器知道该 provider 支持哪些思考强度。',
      '',
      '保存后配置写入 KodaX 共享配置；credential 仍按 Space provider 机制存储。Test connection 会用 SDK provider verification 做一次实际握手。',
    ),
    aliases: [
      '自定义 provider',
      '自定义模型',
      'openai compatible',
      'anthropic compatible',
      'baseURL',
      '自建模型',
      '网关',
    ],
    nextTopics: ['providers', 'config'],
  },
  {
    id: 'settings',
    title: 'Settings',
    summary: 'Settings 分 Preferences、Providers、Runtime、License 四类。',
    body: text(
      'Preferences：显示语言、默认 workspace、Smart Popout Director、原生完成通知、workflow policy。',
      'Providers：内置/custom provider、key 保存与测试、默认 provider、custom provider 管理。',
      'Runtime：KodaX 配置概览、compaction 设置、MCP 全局/项目配置与 reload、Skills 用户/项目目录、安装 skill 文件夹/zip/archive。',
      'License：查看社区/授权/过期/降级状态，导入 .kodax-license，导出授权请求，刷新状态。',
      '',
      'Settings 改 UI 偏好和运行时默认值；会话内临时 model/mode 仍可以通过底部控件或 slash command 调整。',
    ),
    aliases: ['Settings', '设置', '齿轮', 'preferences', 'runtime', 'license', '配置界面'],
    nextTopics: ['providers', 'config', 'mcp', 'skills', 'permissions'],
  },
  {
    id: 'sessions',
    title: 'Projects and sessions',
    summary: '左侧栏管理项目、会话、归档、最近会话和 session 级操作。',
    body: text(
      'Project 是本地工作目录；Session 是围绕某个 project 的连续对话。',
      '',
      '左侧栏可打开/移除/归档项目，项目排序可持久化；展开项目会显示最近会话，更多会话通过 picker overlay 搜索。Session 可以新建、选择、重命名、删除、Fork、Rewind 或通过 /new、/sessions、/load、/delete、/fork、/rewind 等命令管理。',
      '',
      '会话保存模型上下文、工具调用、Artifact、workflow run、计划/Diff/任务等运行状态。跨 KodaX CLI/SDK 共享的历史数据位于 ~/.kodax/sessions。',
    ),
    aliases: [
      'session',
      '项目',
      '会话',
      '侧栏',
      'sidebar',
      'project list',
      '项目列表',
      '左侧栏',
      'history',
    ],
    nextTopics: ['quickstart', 'task-dock', 'command-system'],
  },
  {
    id: 'task-dock',
    title: 'Task Dock',
    summary:
      '右侧 Task Dock 是当前会话的工作状态总览，可跳转到 Plan、Diff、Workflow、Artifact 等细节。',
    body: text(
      '右侧栏默认显示 Task Dock Overview。若当前会话有 artifacts，顶部可在 Overview 与 Artifact 间切换。',
      '',
      'Overview 分区：Run 显示当前运行/项目/session/权限/ask_user/workflow 摘要；Plan 显示计划；Agents 显示本地子 agent/markdown agent；External tasks 显示第三方 Agent 生命周期、输入、取消、对账和审计事件；Workflow 显示当前 run；Changes 显示 git 状态与变更；Sources 显示 working folder；Artifacts 总览产物；Context 显示本 turn 相关工具与文件引用。',
      '',
      '可展开的分区右上角有打开详情按钮，会进入对应 popout。右侧栏可拖拽左缘调整宽度。',
    ),
    aliases: [
      'Task Dock',
      '任务栏',
      '右侧概览',
      'Overview',
      'Run',
      'Changes',
      'Context',
      'Artifacts summary',
    ],
    nextTopics: ['popouts', 'artifacts', 'workflow', 'environment-hub'],
  },
  {
    id: 'popouts',
    title: 'Popout panels',
    summary:
      '右侧 popout 把 Preview、Diff、Terminal、Agents、MCP、Memory、Workflow、Plan、Tasks、Artifact 独立出来。',
    body: text(
      '顶部 activity 菜单可打开 Preview、Diff、Terminal、Agents、MCP、Memory、Workflow。Task Dock 的分区按钮可打开 Plan、Tasks、Artifact 等详情。',
      '',
      'Preview：输入路径或从变更列表打开文件，PDF/DOCX/XLSX 使用 rich preview，其它文本使用 Monaco 只读。',
      'Diff：显示 AI write/edit 修改与 git working tree 差异。',
      'Terminal：真实 PTY 多标签终端，继承项目 cwd，并剥离常见敏感环境变量。',
      'Agents：显示 AGENTS.md/markdown agents 相关信息。',
      'MCP：查看 server 状态、工具、诊断、.mcpb 扩展安装/卸载。',
      'Memory：Coder memory governance，包括 inbox、refs、governance、hints。',
      'Workflow：查看 runs、saved workflows，pause/resume/stop/rerun/rename/delete/save。',
      '',
      'Smart Popout Director 会在首次出现 plan、diff、task 信号时自动打开相应面板，可在 Preferences 关闭。',
    ),
    aliases: [
      'popout',
      '弹出面板',
      '右栏',
      'right sidebar',
      'preview',
      'diff',
      'terminal',
      'mcp panel',
      'memory panel',
    ],
    nextTopics: [
      'smart-popout-director',
      'preview-terminal',
      'mcp',
      'memory-governance',
      'workflow',
    ],
  },
  {
    id: 'smart-popout-director',
    title: 'Smart Popout Director',
    summary: '首次出现 plan/diff/task 信号时自动打开对应面板，避免用户错过关键状态。',
    body: text(
      'Smart Popout Director 是 Space 的 UI 辅助策略：当当前 session 第一次出现计划、文件改动或任务列表信号时，自动打开 Plan、Diff 或 Tasks 面板。',
      '',
      '每类信号每个 session 只自动触发一次，用户手动关闭后不会反复弹出。Settings -> Preferences 可关闭该行为。',
    ),
    aliases: ['smart popout', '自动弹出', 'auto popout', 'popout director', '自动打开面板'],
    nextTopics: ['popouts', 'task-dock'],
  },
  {
    id: 'preview-terminal',
    title: 'Preview and terminal',
    summary: 'Preview 看文件，Terminal 运行真实 shell；两者都从当前项目上下文出发。',
    body: text(
      'Preview 面板用于检查文件内容。PDF、DOCX、XLS/XLSX 会用专门 viewer；其它文本/代码文件用 Monaco 只读查看；超大或不支持文件会显示错误/截断提示。',
      '',
      'Terminal 面板是真实 PTY，多 tab，可在项目 cwd 中运行命令。Windows 默认 cmd.exe，macOS/Linux 走系统 shell。终端环境会剥离常见 *_KEY、*_TOKEN 等敏感变量，降低泄漏风险。',
      '',
      'Preview 适合审阅文件，Terminal 适合用户自己操作环境；AI 需要执行 shell 时仍会走工具权限系统。',
    ),
    aliases: ['预览', 'Preview', '终端', 'Terminal', 'PTY', 'PDF', 'docx', 'xlsx', '文件预览'],
    nextTopics: ['popouts', 'permissions'],
  },
  {
    id: 'artifacts',
    title: 'Artifacts',
    summary: 'Artifact 是 AI 生成的独立产物，可在右侧/弹窗查看、复制、导出、迭代和开独立窗口。',
    body: text(
      'Artifact 用于把“回答中的成果”从聊天流里分离出来，例如 markdown 报告、代码、HTML、interactive HTML、SVG、image、PDF、DOCX、XLSX、chart 等。',
      '',
      'Artifact 视图支持列表选择、版本切换、copy、save/export、再改一版、打开 standalone window。interactive HTML 会进入 sandbox 预览。react artifact 当前是占位类型，不作为可交互 LiveCanvas 运行。',
      '',
      'Artifact 不等于项目文件。它默认是会话产物；需要落到项目里时，用户应明确要求保存到指定路径，之后会走常规写文件权限。',
    ),
    aliases: [
      'Artifact',
      'Artifacts',
      '产物',
      '文档产物',
      'HTML 产物',
      '导出',
      'standalone window',
    ],
    nextTopics: ['task-dock', 'workflow', 'permissions'],
  },
  {
    id: 'workflow',
    title: 'Workflows',
    summary: 'Workflow 管理多步骤任务、运行历史和保存后的可复用流程。',
    body: text(
      'Workflow 适合长任务：拆解、多阶段执行、验证、生成产物、保存流程、复跑历史。',
      '',
      '入口：/workflow 命令、Workflow Launcher、右侧 Workflow 分区、Workflow popout。',
      '',
      'Workflow manager 可查看 active/completed runs 与 saved workflows；支持 pause/resume/stop/rerun、rename/delete、把已完成 run 保存成 workflow、运行 saved workflow。启动 saved workflow 前会做 preflight，并在应用内确认。',
      '',
      'Workflow 面向 Coder session。若当前 Runtime 有可调度的 External Agent，Launcher 可为没有显式 target 的子任务选择默认 Agent，并在启动前按配置修订重新 preflight。危险工具调用仍受 permission mode 和 ask_user 约束。',
    ),
    aliases: ['workflow', '工作流', '/workflow', 'run', 'saved workflow', '复跑', '流程'],
    nextTopics: ['task-dock', 'permissions', 'artifacts'],
  },
  {
    id: 'external-agents',
    title: 'External Agents',
    summary:
      '0.1.31 接入 KodaX 0.7.67 Reference Agent：Runtime 管理、Workflow/Worker 路由和 Task Dock 干预。',
    body: text(
      'Settings -> Runtime -> External Agents 可创建、编辑、启停、删除和实时预检 Reference Agent 注册。Reference 是本地合规适配器，不访问网络、不直接写 Workspace。',
      '',
      'Workflow Launcher 可从实时 listDispatchable 结果中选择默认子 Agent；Space 在启动前再次 preflight 并固定配置修订。Workflow 源码显式声明的 target 优先。KodaX Worker 也通过同一个 opaque agent_id 目录和 executor plane 调度。',
      '',
      'Task Dock 的 External tasks 独立显示 Task State 与 Cancel State、输出、事件时间线和安全的 artifact/usage 摘要；支持回答 input-required、取消以及对 unknown 状态执行 reconcile。',
      '',
      'A2A、MCP Tasks 与受治理 HTTP 适配器不在 KodaX 0.7.67 中，因此 Space 不显示对应注册入口，也不宣称真实远程协议已可用。',
    ),
    aliases: [
      'external agent',
      'third-party agent',
      '第三方 Agent',
      'Reference Agent',
      'Agent Catalog',
      'input-required',
      'reconcile',
    ],
    nextTopics: ['workflow', 'task-dock', 'agent-modes', 'settings'],
  },
  {
    id: 'memory-governance',
    title: 'Memory governance',
    summary: 'Memory 面板管理 Coder 记忆建议、已批准引用、治理报告和任务 hints。',
    body: text(
      'Memory popout 是 Coder-only 的记忆治理界面。需要当前有活跃 Coder session。',
      '',
      'Inbox：查看待批准 memory proposals，按 fingerprint guard 审核 approve/reject，并可给拒绝理由。',
      'Refs：检查已批准记忆引用。',
      'Governance：运行 curator/report，发现过期、冲突或可合并信息。',
      'Hints：为当前任务构建 memory pack/hints，帮助模型在后续 turn 使用稳定上下文。',
      '',
      'Partner 的 Knowledge Base 是单独的产品面，不等同于 Coder memory governance；Partner 当前已启用。',
    ),
    aliases: [
      'memory',
      '记忆',
      'Memory Governance',
      '记忆治理',
      'hints',
      'refs',
      'learn',
      '/memory',
      '/learn',
    ],
    nextTopics: ['popouts', 'partner', 'config'],
  },
  {
    id: 'permissions',
    title: 'Permissions and ask_user',
    summary: '权限模式控制写文件/命令等风险操作；ask_user 用模态框向用户确认信息。',
    body: text(
      '权限模式：Plan 尽量只读和计划；Accept Edits 日常推荐，写文件/命令等风险操作会确认；Auto 放行更多操作，适合可信项目和明确规则。',
      '',
      '切换方式：底部 ModeSelector、Shift+Tab 循环、Ctrl+M 打开选择器、/mode plan|accept-edits|auto。',
      '',
      '当 AI 请求写文件、编辑、运行 bash、MCP 副作用工具等操作时，Space 会弹权限 modal，可 Allow once、Allow always 或 Deny；多个请求可能批量展示。',
      '',
      'ask_user 是模型主动向用户确认问题的通道，Space 会显示选择题或文本输入 modal。带 Other/自定义输入的问题可由用户填自由文本再继续。',
    ),
    aliases: [
      '权限',
      'permission',
      'allow',
      '允许',
      '弹窗',
      'plan mode',
      'accept edits',
      'auto mode',
      'ask_user',
      '确认',
    ],
    nextTopics: ['agent-modes', 'workflow', 'tools'],
  },
  {
    id: 'agent-modes',
    title: 'Agent modes and agents',
    summary: '底部可选 AMA、AMAW、SA；Agent picker 可插入项目/用户 markdown agents。',
    body: text(
      'Agent Mode Selector 控制会话采用的协作形态：AMA 是默认多 agent 编排；AMAW 是自动 workflow 取向；SA 是 single-agent 模式。实际行为由 SDK 和当前可用工具共同决定。',
      '',
      'Agent picker 会读取用户目录和项目目录下的 markdown agents，选择后向 composer 插入 @agent-name。AGENTS.md 和 markdown agents 主要用于给模型补充角色、规则和项目约定。',
      '',
      'Agents popout/Task Dock 会显示当前会话相关 agent 状态。',
    ),
    aliases: [
      'agent mode',
      'agent',
      'agents',
      'AMA',
      'AMAW',
      'SA',
      'markdown agent',
      '@agent',
      'AGENTS.md',
    ],
    nextTopics: ['composer', 'tools', 'workflow'],
  },
  {
    id: 'tools',
    title: 'Agent tools',
    summary:
      'Coder 可用读写、shell、web、artifact、workflow、MCP、memory 等工具；副作用工具受权限约束。',
    body: text(
      'Coder session 使用 SDK 工具集：文件读取/搜索、代码索引、编辑/写入、bash、web_search/web_fetch、artifact 创建、workflow、MCP、memory 等。',
      '',
      '只读工具通常直接运行；写文件、执行命令、会改外部状态的 MCP 工具或敏感操作会进入权限确认。',
      '',
      'create_artifact 生成会话产物，不直接改项目文件。repo-intelligence 是只读仓库理解能力。MCP 工具的可用性取决于 server 状态与工具副作用声明。',
      '',
      'Partner 已启用 workspace-first Outputs、Sources/KB、checkpointed writes、Office/PDF 便利产物和 reviewed strict fallback；它不等于 Coder 的完整 coding toolset，也不宣称尚未交付的 Connector、浏览器控制或自动化能力。',
    ),
    aliases: [
      'tools',
      '工具',
      'tool',
      '能用什么工具',
      'agent tools',
      'read tool',
      'bash tool',
      'web_search',
    ],
    nextTopics: ['permissions', 'mcp', 'repo-intelligence', 'artifacts'],
  },
  {
    id: 'mcp',
    title: 'MCP and extensions',
    summary: 'MCP 面板查看 server 状态、工具、诊断和 .mcpb 扩展；Runtime 设置可 reload 配置。',
    body: text(
      'MCP 面板显示 configured MCP servers：idle/connecting/ready/error/disabled 状态、command/url、start/stop、工具列表、诊断信息。',
      '',
      '面板可 Refresh、Reload config、Install extension。已安装 .mcpb 扩展可查看和 uninstall；配置错误会显示并可 reveal 配置路径。',
      '',
      'Settings -> Runtime 也能查看 global/project MCP 配置并 reload。/mcp 或 /extensions 可作为命令入口。',
      '',
      'SDK filesystem extensions 与 MCP 是两个概念。/extensions sdk 用于查看 SDK 扩展发现/加载诊断；默认安全策略是发现优先，执行扩展代码需要显式 opt-in。',
    ),
    aliases: [
      'mcp',
      'model context protocol',
      'mcp server',
      '.mcpb',
      '外部工具',
      'integration',
      'extensions',
      '插件',
    ],
    nextTopics: ['tools', 'settings', 'permissions'],
  },
  {
    id: 'extensions',
    title: 'Extensions',
    summary: '/extensions 汇总 Space MCP 扩展和 SDK 扩展诊断；执行第三方扩展需可信来源。',
    body: text(
      'Space 的扩展面主要有两类：',
      '',
      '1. MCP/.mcpb：通过 MCP 面板安装、查看、启动/停止、卸载，能力会以 MCP tools 暴露给 agent。',
      '2. SDK filesystem extensions：通过 /extensions sdk 查看默认目录、entrypoint、skipped entries 和运行时诊断。默认偏向 discovery-only，加载用户扩展代码需要显式启用。',
      '',
      '只从可信来源安装扩展。会改状态或访问外部资源的扩展工具仍应受权限模式、MCP 工具声明和用户确认约束。',
    ),
    aliases: [
      'extension',
      'extensions',
      'plugin',
      'plugins',
      'sdk extensions',
      '/extensions',
      '扩展',
      '插件',
    ],
    nextTopics: ['mcp', 'permissions', 'settings'],
  },
  {
    id: 'skills',
    title: 'Skills',
    summary:
      'Skill 是 SDK 级能力，Space 在 composer 的 / 补全和 Runtime 设置中暴露安装与调用入口。',
    body: text(
      'Skill 位于用户或项目的 .kodax/skills 目录，由 SDK SkillRegistry 注入会话。',
      '',
      '调用：在 composer 输入 /，skill 会和 slash command 一起出现在补全列表。若名称冲突，可用 /skill:<name> 消歧。',
      '',
      '安装/管理：Settings -> Runtime -> Skills 显示用户/项目 skill 目录，并可安装文件夹、zip 或 archive。skill-creator 也可生成新的 skill；Space 会在补全打开时刷新 registry，让新 skill 尽快可见。',
      '',
      'Skill 是“教 agent 如何做事”的说明，不等同于 MCP 外部工具。',
    ),
    aliases: ['skill', 'skills', '技能', 'skill creator', '生成 skill', '加 skill', '/skill'],
    nextTopics: ['slash-commands', 'settings', 'tools'],
  },
  {
    id: 'slash-commands',
    title: 'Slash commands',
    summary:
      '输入 / 打开命令/skill 补全；常用命令覆盖 session、mode、provider、workflow、memory、MCP 和诊断。',
    body: text(
      'composer 输入 / 会打开补全；Tab/Enter 可接受补全，Esc 关闭，箭头键导航。',
      '',
      '常用命令：/help、/new、/clear、/copy、/history、/sessions、/load、/delete、/fork、/rewind；/mode、/provider、/model、/reasoning、/thinking、/agent-mode；/workflow；/memory、/learn；/extensions、/mcp；/repointel、/doctor、/status、/review；/compact、/tree、/paste、/reload。',
      '',
      '可用命令会随版本、当前 session、项目和 provider 状态变化，以 /help 与补全列表为准。',
    ),
    aliases: ['slash', '/', '命令', 'slash command', '快捷命令', '/help', '/workflow', '/mode'],
    nextTopics: ['command-system', 'skills', 'keyboard-shortcuts'],
  },
  {
    id: 'command-system',
    title: 'Command palette and help',
    summary: 'Ctrl/Cmd+Shift+P 是全局命令面板；? 打开帮助；/ 是 composer 内命令。',
    body: text(
      'Space 有三类命令入口：',
      '',
      'Command Palette：Ctrl/Cmd+Shift+P 打开，搜索 action、最近 session、文件引用和 slash 命令。适合快速切换视图、会话、主题、面板或执行全局动作。',
      'Slash commands：在 composer 输入 /，把命令作为当前消息/会话的一部分执行。',
      'Help overlay：按 ? 打开帮助，查看常用快捷键和入口。',
      '',
      '这三者不是同一层：Command Palette 操作 UI；slash command 进入 agent/session 命令系统；Help 用来查询。',
    ),
    aliases: [
      '命令面板',
      'command palette',
      'Ctrl+Shift+P',
      'Cmd+Shift+P',
      '帮助',
      'help overlay',
      '?',
    ],
    nextTopics: ['slash-commands', 'keyboard-shortcuts'],
  },
  {
    id: 'image-paste',
    title: 'Image paste',
    summary: 'composer 可粘贴/拖入 PNG、JPEG、WEBP 图片，作为 multimodal 输入发送。',
    body: text(
      '在 composer 中直接粘贴截图或拖入 PNG/JPEG/WEBP 图片，会显示缩略图 chip。发送时 Space 将图片作为 input artifact 传给 SDK，支持 vision 的 provider/model 会收到 multimodal content。',
      '',
      '限制：单张约 6 MiB，单轮最多 8 张。GIF/视频不保证作为动态图或视频处理。发送前可移除图片 chip。',
    ),
    aliases: [
      '粘图',
      '粘贴图片',
      '截图',
      'paste image',
      'image input',
      '多模态',
      'multimodal',
      'vision',
      '看图',
    ],
    nextTopics: ['composer', 'providers'],
  },
  {
    id: 'quick-ask',
    title: 'Quick Ask',
    summary: 'Ctrl/Cmd+K 打开临时 plan-mode 问答；可 Continue in Coder 提升为正常会话。',
    body: text(
      'Quick Ask 适合临时问一句，不想打断当前主会话时使用。它需要已打开项目，会创建临时 plan-mode code session，流式回答后关闭时会清理临时 session。',
      '',
      '如果答案值得继续推进，点击 Continue in Coder 会把内容提升/接入正常 Coder session 并选中它。',
      '',
      '注意：Quick Ask 不是完全无 session 的 side query；它是受限制的临时 session，默认偏只读。',
    ),
    aliases: ['Quick Ask', 'quick ask', 'Ctrl+K', 'Cmd+K', '临时问答', '快速提问', 'side query'],
    nextTopics: ['sessions', 'permissions', 'keyboard-shortcuts'],
  },
  {
    id: 'environment-hub',
    title: 'Environment Hub',
    summary: '顶部环境按钮显示当前项目、git 状态、运行上下文和来源，并能跳转到 Task Dock 分区。',
    body: text(
      'Environment Hub 是顶部紧凑状态入口。它显示当前项目、git branch/changes/ahead/behind、本地工作位置、sources/session context 等摘要。',
      '',
      '点击后可跳转到 Task Dock 的 Changes、Sources、Run、Context 等分区。git 状态会在窗口 focus、visibility 变化和定时刷新时更新。',
      '',
      '当前主要支持本地 workspace。worktree/cloud 位置入口仍是禁用或后续能力。',
    ),
    aliases: ['Environment Hub', '环境', '顶部状态', 'git 状态', 'workspace', 'sources', 'changes'],
    nextTopics: ['task-dock', 'sessions', 'repo-intelligence'],
  },
  {
    id: 'handoff',
    title: 'Handoff inbox',
    summary: '标题栏 handoff inbox 会接收 ~/.kodax/handoffs 中的会话交接描述。',
    body: text(
      '当 ~/.kodax/handoffs 下存在 handoff 描述时，标题栏会出现 inbox。它会显示有效/总数、stale/error 状态，并允许 accept 或 dismiss。',
      '',
      'Accept 前会验证目标 session 仍存在；成功后移除 descriptor 并切到对应会话。Dismiss 会丢弃该 handoff 描述。',
    ),
    aliases: ['handoff', '交接', 'inbox', 'thread handoff', '会话交接'],
    nextTopics: ['sessions', 'workflow'],
  },
  {
    id: 'partner',
    title: 'Partner surface status',
    summary:
      'Partner surface is available with workspace-first Outputs, checkpointed workspace writes, KB, sources, artifacts, and local policy/audit controls.',
    body: text(
      'Space 有 Coder 与 Partner 两个 surface 概念。Coder 是当前可用的主要工作区。',
      '',
      'Partner includes Sources, Conversation, Artifact/Knowledge Base, Outputs, checkpointed workspace-session writes, generated Office/PDF convenience artifacts, reviewed strict fallbacks, and local policy/audit controls.',
      '',
      'PARTNER_ENABLED is true. The Partner tab is available, and Partner sessions can be restored like other surface-scoped sessions.',
    ),
    aliases: [
      'Partner',
      'partner',
      '伙伴',
      'Knowledge Base',
      'Sources Panel',
      'Partner 不可用',
      '开发中',
    ],
    nextTopics: ['overview', 'memory-governance', 'artifacts'],
  },
  {
    id: 'repo-intelligence',
    title: 'Repository intelligence',
    summary: 'repo-intelligence 为当前项目提供只读仓库理解、符号/模块上下文和预热诊断。',
    body: text(
      '打开项目后，SDK 可按需使用 repo-intelligence：仓库概览、符号查找、模块上下文、文件/引用理解等。',
      '',
      'composer 首次输入时可能 best-effort prewarm 当前项目；/repointel status 或 /repointel warm 可查看/预热诊断。',
      '',
      '这是一组只读能力，不直接修改文件。可用性可能受项目结构、SDK 状态和 license/policy 控制。',
    ),
    aliases: [
      'repo intelligence',
      'repointel',
      '仓库智能',
      '代码索引',
      'symbol',
      '项目结构',
      'codebase',
      '/repointel',
    ],
    nextTopics: ['tools', 'environment-hub', 'sessions'],
  },
  {
    id: 'config',
    title: 'Config and data locations',
    summary:
      'Space 使用 ~/.kodax/space 保存 UI 状态，也复用 ~/.kodax 的 SDK 配置、sessions、skills、MCP。',
    body: text(
      '~/.kodax/ 是 SDK/CLI/Space 共享层：config、sessions、skills、MCP、AGENTS.md 等。',
      '',
      '~/.kodax/space/ 是 Space 专属层：UI state、main logs、桌面端偏好等。',
      '',
      '项目级配置通常位于项目内 .kodax 或 AGENTS.md。Settings -> Runtime 会展示 KodaX config、compaction、MCP、Skills 等运行时状态。',
      '',
      '一般不要手动改 state 文件；若 UI 状态严重损坏，可在备份后重置 ~/.kodax/space/state.json。',
    ),
    aliases: [
      '配置文件',
      '数据目录',
      '存哪',
      'config location',
      'data path',
      '~/.kodax',
      '~/.kodax/space',
      'state.json',
    ],
    nextTopics: ['settings', 'providers', 'troubleshooting'],
  },
  {
    id: 'sidebar-resize',
    title: 'Resize and zoom',
    summary: '左右栏可拖宽；Ctrl+wheel、Ctrl+=、Ctrl+-、Ctrl+0 控制全局缩放。',
    body: text(
      '左侧栏右缘和右侧栏左缘有 resize handle，可拖拽调整宽度；双击通常恢复默认；拖动中 Esc 可取消。',
      '',
      '全局缩放：Ctrl+wheel、Ctrl+=/Ctrl+- 增减，Ctrl+0 重置。右下角会短暂显示当前 zoom factor。',
      '',
      'Transcript 另有视图菜单，可切 Normal/Thinking/Verbose/Summary 和 small/base/large 文本大小；Ctrl+Shift+O 可打开/切换。',
    ),
    aliases: [
      '缩放',
      'zoom',
      '调字号',
      '改大小',
      '拖栏',
      '拖宽',
      '侧栏宽度',
      'sidebar width',
      'resize',
    ],
    nextTopics: ['keyboard-shortcuts', 'ui-map'],
  },
  {
    id: 'keyboard-shortcuts',
    title: 'Keyboard shortcuts',
    summary: '常用快捷键覆盖发送、补全、Quick Ask、命令面板、权限模式、reasoning、面板和缩放。',
    body: text(
      '发送与 composer：Enter 发送，Shift+Enter 换行，Ctrl/Cmd+Enter after-turn 排队，Esc 停止/关闭当前 popover；/ 打开 slash 补全，@ 打开路径补全。',
      '全局：Ctrl/Cmd+K Quick Ask；Ctrl/Cmd+Shift+P 命令面板；? Help；Ctrl+Shift+O Transcript view menu。',
      '模式：Shift+Tab 循环 permission mode；Ctrl+M 打开 permission mode picker；Ctrl+T 循环 reasoning effort。',
      '面板：Ctrl+Shift+V Preview；Ctrl+Shift+D Diff；Ctrl+` Terminal（若平台/菜单映射可用）。',
      '缩放：Ctrl+wheel、Ctrl+=、Ctrl+-、Ctrl+0。',
      'Mac 文本编辑使用 Cmd+C/V/X/Z/Shift+Z；Windows/Linux 使用 Ctrl 对应组合。',
    ),
    aliases: ['快捷键', 'shortcut', 'keybinding', '键盘', '热键', 'hotkey', 'Cmd+K', 'Ctrl+K'],
    nextTopics: ['command-system', 'composer', 'sidebar-resize'],
  },
  {
    id: 'troubleshooting',
    title: 'Troubleshooting',
    summary:
      '优先看 Settings/Providers、MCP diagnostics、DevTools console 和 ~/.kodax/space/logs。',
    body: text(
      '常见问题：',
      '- No provider/key：到 Settings -> Providers 配 key，或确认环境变量。',
      '- AI 读不到文件：确认已打开项目目录，路径引用是否在 workspace 内。',
      '- Partner 不可点：0.1.30+ 正常应启用；检查版本、当前 surface 和本地状态，并查看 DevTools/logs。',
      '- External Agent 不可选：确认使用 0.1.31 开发候选版、Reference 注册已启用且实时 preflight 通过；A2A/MCP Tasks/HTTP 当前不会出现。',
      '- Quick Ask 不工作：需要先打开项目；它使用临时 plan-mode session。',
      '- MCP 工具不可见：打开 MCP 面板 Refresh/Reload config，查看 server error/diagnostics。',
      '- 语言切换后仍有英文：模型输出、日志、专业面板和 provider 内容可能仍保留英文。',
      '- UI 状态异常：检查 ~/.kodax/space/logs 与 DevTools console；极端情况备份并重置 ~/.kodax/space/state.json。',
      '',
      '反馈 bug 时提供版本号、项目状态、复现步骤、相关日志和截图。',
    ),
    aliases: [
      '问题',
      '排错',
      'troubleshoot',
      'debug',
      '日志',
      'log',
      '报错',
      'error',
      '白屏',
      '卡死',
    ],
    nextTopics: ['config', 'providers', 'mcp'],
  },
];
